# Azure DevOps Pipeline

name: $(Date:yyyyMMdd)$(Rev:r)

variables:
  vmImage: 'ubuntu-latest'
  dockerImageName: 'orneholmbirdornotweb'

trigger:
- master

stages:
- stage: BuildWebImage
  displayName:  'Build web image'
  dependsOn: []
  jobs:
  - job: BuildWebImage
    displayName: 'Build'

    pool:
      vmImage: '$(vmImage)'

    variables:
      pathToPublishProjects: '**/src/**/*.*sproj'

    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(imageName)
        command: build
        Dockerfile: app/Dockerfile

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: '$(artifactName)'
